# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: Wes Fairhead
title: UI/UX Developer
#subtitle: 'UI/UX Developer'
email: wfairhead@gmail.com
descriptionn: UI/UX Developer
location: Lincoln, Nebraska
phone: 402.309.4653
sitetitle: Professional Portfolio
github: https://github.com/westerfer/
linkedIn: https://www.linkedin.com/in/wes-fairhead-0277b06b/
description: Hi, my name is Wes Fairhead. As a designer, it’s hard to focus on anything other than the design of the project. With time and experience I've discovered that there needs to be a strong relationship between both business logic and design to create a great user experience.

baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll
disqus:
    shortname: wfairhead
google_analytics: UA-74351809-1UPDATE
google_tag_manager: GTM-M3842PXUPDATE

# Build settings
markdown: kramdown
permalink: /articles/:title
collections:
    projects:
        output: true
# theme: minima
autoprefixer:
    browsers:
        - last 2 versions
plugins:
    - jekyll-feed
    - jekyll-autoprefixer

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - webpack.config.js
    - package.json
    - package-lock.json
    - webpack
