# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
author: Wes Fairhead
title: Frontend Developer
email: wfairhead@gmail.com
location: Lincoln,&nbsp;Nebraska
city: Lincoln
state: Nebraska
phone: 402.309.4653
sitetitle: Professional Portfolio
description: Hi, my name is Wes Fairhead. Through my 6 years of development experience, I've discovered that there needs to be a strong relationship between business logic, development and design to create a great application or website.
github: https://github.com/westerfer/
linkedIn: https://www.linkedin.com/in/wes-fairhead-0277b06b/

baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://westerfer.netlify.app/' #
#google_analytics: UA-163408901-1

# Work
work1-title: Department of Revenue
work1-description: Website, UI/UX, Reorganization, Development
work1-link: https://revenue.nebraska.gov/

work2-title: Administrative Services
work2-description: Website, UI/UX, Reorganization, Development
work2-link: https://link.nebraska.gov/

work3-title: Lewis &amp; Clark Natural Resource District
work3-description: Website, UI/UX, Reorganization, Development, Logo Design
work3-link: https://lcnrd.nebraska.gov/

work4-title: Nebraska.gov
work4-description: Website, UI/UX, Reorganization, Development
work4-link: https://www.nebraska.gov/

work5-title: State Records Board
work5-description: Website, UI/UX, Development
work5-link: https://staterecordsboard.nebraska.gov/

work6-title: Nebraska Interactive
work6-description: Website, Development
work6-link: http://www.nebraska-interactive.com/

worklink-title: View Website


# Metatag Details
home_meta: One of most important rules that I like to follow when developing a user interface or creating that perfect experience. However, there's a certain point in every design where this rule, like many others, is meant to be broken.
about_meta: With time and experience I've discovered that there needs to be a strong relationship between both business logic and design to create a great user experience.
work_meta: Research. Design. Execute. I like to fully research any project and have all questions answered before development starts.
resume_meta: I'm a UI/UX Developer with over 5 years of experience in design and development.
contact_meta: Hi! I'm Wes Fairhead and I'm a UI/UX Developer. Traveling, gardening, animals and coding are my jam Get in touch with me today!


# Build settings
markdown: kramdown
permalink: /articles/:title
collections:
    projects:
        output: true
# theme: minima
autoprefixer:
    browsers:
        - last 2 versions
plugins:
    - jekyll-feed
    - jekyll-autoprefixer

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - webpack.config.js
    - package.json
    - package-lock.json
    - webpack
